- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 14400 # 4 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 # 4 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400 # 4 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hrs
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
    pocket1: WeaponPistolN1984
  storage:
    back:
    - MagazineMagnum
    - Flash
    - TelescopicBaton # Goobstation
    # - StationCharter
