- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Amber
  # - Bagel
  # - Box
  - Cluster
  # - Cog # Goobstation - cog is broken
  # - Core
  # - Fland
  # - Gate
  # - Loop # ShibaStation - Loop is cringe
  # - Marathon
  # - Meta
  # - Oasis # ShibaStation - Oasis is broken sad face
  - Omega
  # - Origin
  - Saltern
  - Packed
  # - Reach # ShibaStation - FUCK REACH FUCK REACH FUCK REACH
  # - Train # Goobstation - all my friends hate train
  # - FlandHighPop
  # - OasisHighPop
  # - Barratry # Goobstation - Re-add barratry
  # - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  # - Submarine # goobstation - kill yourself
  # - Leonid # Goobstation - for goob by goob
  - Elkridge # ShibaStation - Elkridge
