- type: job
  id: BlueshieldOfficer
  name: Blueshield Officer
  description: "Act as a bodyguard and advisor for Command and CentComm VIPs."
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hrs
    - !type:AgeRequirement
      requiredAge: 21
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    eyes: ClothingEyesGlassesMedSec
    gloves: ClothingHandsGlovesCombat
    id: BlueshieldPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltSecurityFilled
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
    pocket2: PinpointerNuclear
    suitstorage: WeaponLeverChester
  storage:
    back:
    - Flash
    - BlueshieldAmmunitionBoxFilled
    - BluespaceLifelineImplanter
    - WeaponEnergyRevolver
    - SecHypo
