- type: job
  id: NanotrasenRepresentative
  name: NT Representative
  description: "Represent NanoTrasen, send reports back to them on the station's situation, inform the heads of anything CentComm orders them to do."
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hrs
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - Service
  - Hydroponics
  - Kitchen
  - Cargo
  - Theatre
  - NanotrasenRepresentative
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: NanotrasenRepresentativeGear
  equipment:
    id: NTRepPDA
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesGoldenTrim # Psst. I might as well add this here.
    pocket1: UniqueNanorepLockerTeleporter
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation
