- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements: # ShibaStation - Antag Playtime Requirements
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5 hours

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - ToolboxThief
    - ClothingHandsChameleonThief
