- type: antag
  id: InitialInfected
  name: roles-antag-initial-infected-name
  antagonist: true
  setPreference: true
  objective: roles-antag-initial-infected-objective
  requirements:
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10 hours
  guides: [ Zombies ]

- type: antag
  id: Zombie
  name: roles-antag-zombie-name
  antagonist: true
  setPreference: false
  objective: roles-antag-zombie-objective
  requirements:
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
  guides: [ Zombies ]
