- type: antag
  id: Heretic
  name: roles-antag-heretic-name
  antagonist: true
  setPreference: true
  objective: roles-antag-heretic-description
  requirements: # ShibaStation - Antag Playtime Requirements
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10 hours
  guides: [ Heretics ]

- type: startingGear
  id: HereticGear
  storage:
    back:
    - CodexCicatrix
    - OrganHumanHeart
