- type: antag
  id: Blob
  name: roles-antag-blob-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blob-objective
  guides: [ Blob ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 180000 # 50 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 # 20 hours
